(define byeoru-on-key '("<Shift> "))
(define byeoru-on-key? (make-key-predicate '("<Shift> ")))
(define byeoru-latin-key '("<Control> "))
(define byeoru-latin-key? (make-key-predicate '("<Control> ")))
(define byeoru-conversion-key '("F9"))
(define byeoru-conversion-key? (make-key-predicate '("F9")))
(define byeoru-commit-key '("return"))
(define byeoru-commit-key? (make-key-predicate '("return")))
(define byeoru-cancel-key '("escape"))
(define byeoru-cancel-key? (make-key-predicate '("escape")))
